/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.checks.template.toml --include-runtime=false src/env.d.ts` (hash: 3bf284aadca3981d90663b1f40f9c98a)
interface __BaseEnv_Env {
  CONTROL_DB: D1Database;
  TELEMETRY_DB: D1Database;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface ProductionEnv {
    CONTROL_DB: D1Database;
    TELEMETRY_DB: D1Database;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
