/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.checks.template.toml --env-file=.dev.vars.example --include-runtime=false src/env.d.ts` (hash: 0dfe7e851d727310d4bed993895a90da)
interface __BaseEnv_Env {
  CONTROL_DB: D1Database;
  TELEMETRY_DB: D1Database;
  CHECK_SECRET_WRAPPING_KEY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface ProductionEnv {
    CONTROL_DB: D1Database;
    TELEMETRY_DB: D1Database;
    CHECK_SECRET_WRAPPING_KEY: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
