/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.notifications.template.toml --env-file=.dev.vars.example --include-runtime=false src/env.d.ts` (hash: 298dd1336e78e3173cc2404d67fe8f6d)
interface __BaseEnv_Env {
  CONTROL_DB: D1Database;
  TELEMETRY_DB: D1Database;
  NOTIFICATION_SECRET_WRAPPING_KEY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface ProductionEnv {
    CONTROL_DB: D1Database;
    TELEMETRY_DB: D1Database;
    NOTIFICATION_SECRET_WRAPPING_KEY: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
