/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.web.template.toml --env-file=.dev.vars.example --include-runtime=false src/worker-env.d.ts` (hash: 6917fcb9ef4c732b77336920faaeb0c5)
interface __BaseEnv_Env {
  CONTROL_DB: D1Database;
  TELEMETRY_DB: D1Database;
  ASSETS: Fetcher;
  INGEST_ORIGIN: "https://ingest.example.com";
  BETTER_AUTH_SECRET: string;
  SETUP_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("../.svelte-kit/cloudflare/_worker");
  }
  interface ProductionEnv {
    CONTROL_DB: D1Database;
    TELEMETRY_DB: D1Database;
    ASSETS: Fetcher;
    INGEST_ORIGIN: "https://ingest.example.com";
    BETTER_AUTH_SECRET: string;
    SETUP_TOKEN: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, "INGEST_ORIGIN" | "BETTER_AUTH_SECRET" | "SETUP_TOKEN">
    > {}
}
