/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.web.template.toml --env-file=.dev.vars.example --include-runtime=false src/worker-env.d.ts` (hash: bbb6c6a64f95b46de0f226861b1d0183)
interface __BaseEnv_Env {
  CONTROL_DB: D1Database;
  TELEMETRY_DB: D1Database;
  ASSETS: Fetcher;
  INGEST_ORIGIN: "https://ingest.example.com";
  LIVE_ORIGIN: "wss://live.example.com";
  AGENT_RELEASE_MANIFEST_JSON: '{"linux-x86_64":{"version":"0.1.0","length":0,"sha256":"0000000000000000000000000000000000000000000000000000000000000000"}}';
  BETTER_AUTH_SECRET: string;
  SETUP_TOKEN: string;
  ENROLLMENT_TOKEN_PEPPER: string;
  CHECK_SECRET_WRAPPING_KEY: string;
  LIVE_TICKET_SECRET: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("../.svelte-kit/cloudflare/_worker");
  }
  interface ProductionEnv {
    CONTROL_DB: D1Database;
    TELEMETRY_DB: D1Database;
    ASSETS: Fetcher;
    INGEST_ORIGIN: "https://ingest.example.com";
    LIVE_ORIGIN: "wss://live.example.com";
    AGENT_RELEASE_MANIFEST_JSON: '{"linux-x86_64":{"version":"0.1.0","length":0,"sha256":"0000000000000000000000000000000000000000000000000000000000000000"}}';
    BETTER_AUTH_SECRET: string;
    SETUP_TOKEN: string;
    ENROLLMENT_TOKEN_PEPPER: string;
    CHECK_SECRET_WRAPPING_KEY: string;
    LIVE_TICKET_SECRET: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "INGEST_ORIGIN"
        | "LIVE_ORIGIN"
        | "AGENT_RELEASE_MANIFEST_JSON"
        | "BETTER_AUTH_SECRET"
        | "SETUP_TOKEN"
        | "ENROLLMENT_TOKEN_PEPPER"
        | "CHECK_SECRET_WRAPPING_KEY"
        | "LIVE_TICKET_SECRET"
      >
    > {}
}
