ALTER TABLE agents ADD COLUMN hostname TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN os_name TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN os_version TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN kernel_version TEXT NOT NULL DEFAULT '';
