/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.retention.template.toml --include-runtime=false src/env.d.ts` (hash: a79b28c533a96154c9194bbc6edb1110)
interface __BaseEnv_Env {
  EXPORT_BUCKET: R2Bucket;
  CONTROL_DB: D1Database;
  TELEMETRY_DB: D1Database;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface ProductionEnv {
    EXPORT_BUCKET: R2Bucket;
    CONTROL_DB: D1Database;
    TELEMETRY_DB: D1Database;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
