/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.live.template.toml --env-file=.dev.vars.example --include-runtime=false src/env.d.ts` (hash: c7b28d9130dbb73b3d84fccc7788b2b0)
interface __BaseEnv_Env {
  LIVE_TICKET_SECRET: string;
  LIVE_HUBS: DurableObjectNamespace<import("./index").LiveHub>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
    durableNamespaces: "LiveHub";
  }
  interface ProductionEnv {
    LIVE_TICKET_SECRET: string;
    LIVE_HUBS: DurableObjectNamespace<import("./index").LiveHub>;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
